name: electron-python-sample
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - retina-face>=0.0.14
      - tf-keras
      # YOLO face models downloaded from: https://github.com/cardiff-babylab/tinyexplorer-detection-app/releases/tag/v1.0.0-models
      # (originally from https://github.com/akanametov/yolo-face)
      - opencv-python
      - pillow
      - numpy
      - torch
      - torchvision
      - flask
      - flask-cors
      - flask-graphql
      - flask-socketio
      - graphene
      - ultralytics
      - tensorflow